export const dummyData = {
  agreement: true as const,

  step1: {
    q1: "John Doe",
    q2: "johndoe@example.com",
    q3: "+1234567890",
    q4: "1990-01-01",
    q5: "Male",
    q6: "American",
    q7: "123 Main St",
    q8: "Apt 4B",
    q9: "New York",
    q10: "USA",
  },
  step2: {
    q1: "Bachelor's Degree",
    q2: "Computer Science",
    q3: "University of Technology",
    q4: "2012",
    q5: "Software Engineer",
    q6: "Tech Solutions Inc.",
    q7: "Senior Developer",
    q8: "8",
    q9: "JavaScript, React, Node.js",
    q10: "English, Spanish",
  },
  step3: {
    q1: "Reading, Hiking, Photography",
    q2: "The Hitchhiker's Guide to the Galaxy",
    q3: "Inception",
    q4: "Rock",
    q5: "Dog",
    q6: "Vegetarian",
    q7: "3 times a week",
    q8: "Moderate",
    q9: "Local animal shelter",
    q10: "Start a tech company",
  },
};
